### ISSUE TITLE
Is  desc  folder missing?

### ISSUE THREAD

**Issue by meanna** [JULIELab/smithsearch#10]
Hello, 

Is `smithsearch/indexing-pipeline/desc` missing or is it supposed to be generated by some code?

Thank you!

**Comment by khituras** [comment]
Hello there,

the `desc` directory is created upon saving the pipeline with the [JCoRe Pipeline Builder](https://github.com/JULIELab/jcore-pipeline-modules). The same holds for the `lib` directory.

Hope this helps!
