### ISSUE TITLE
Source of entity dictionary

### ISSUE THREAD

**Issue by meanna** [JULIELab/smithsearch#12]
Do you create the entity dictionary based on any medical database?

Thanks!

**Comment by khituras** [comment]
In SMITH we used a custom dictionary that was derived from the ICD10 catalogue. But this is not a necessity to this project, you can use any dictionary for your purpose. It just needs two tab-separated columns. The first column holds the word, the second column holds the ID of the concept. This was the ICD10 code in our work.
