### ISSUE TITLE
local path in  aeDescriptions.json

### ISSUE THREAD

**Issue by meanna** [JULIELab/smithsearch#14]
Hello, 

in aeDescriptions.json, there is path to local file.

`"file":"D:\\Users\\faessler\\.m2\\repository\\de\\julielab\\jcore-jsbd-ae-medical-german\\2.6.0\\jcore-jsbd-ae-medical-german-2.6.0.jar"
`
To get this jar file, do I have to download the whole [jcore-projects](https://github.com/JULIELab/jcore-projects) and build [jcore-jsbd-ae-medical-german-2.6.0.jar ?](https://github.com/JULIELab/jcore-projects/tree/master/jcore-jsbd-ae-medical-german) ?

Thank you!

**Comment by khituras** [comment]
This file - as most other pipelines files - is auto-generated by the [JCoRe Pipeline Modules](https://github.com/JULIELab/jcore-pipeline-modules) **upon saving the pipeline**. I.e. you need to open the pipeline with the pipeline editor and save it. This will download all the JAR files into the `lib/` directory.
