### ISSUE TITLE
How to get jsbd-2.0.gz ?

### ISSUE THREAD

**Issue by meanna** [JULIELab/smithsearch#16]
I tried creating and running a pipeline and got this error.

`Caused by: java.lang.IllegalArgumentException: The model file "de/julielab/jcore/ae/jsbd/model/jsbd-2.0.gz" could be found neither in the file system nor in the classpath.`

In 
`jcore-jsbd-ae/README.md`, it says that the model is not included.

> \* a model is not included; see the [biomed-project](https://github.com/JULIELab/jcore-projects/tree/master/jcore-jsbd-ae-biomedical-english) or [medical-project](https://github.com/JULIELab/jcore-projects/tree/master/jcore-jsbd-ae-medical-german) for a pre-built one

How should I do ?

Thank you!

**Comment by khituras** [comment]
To resolve the issue, please see my answer in #15.

For the general case: You answered the question yourself, you postet the links the the jcore-projects where specific models are available.
